services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8585:8585"
    volumes:
      - /home/cristian_martin/monitocam_recordings:/recordings
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
