FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg libpam0g libpam-modules libpam-runtime passwd && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

ENV PYTHONPATH=/app/src

RUN mkdir -p /home/cristian_martin/monitocam_recordings

RUN useradd -m -s /bin/bash admin && echo 'admin:admin' | chpasswd

EXPOSE 8585

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8585"]
