services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8585:8585"
    volumes:
      - /mnt/nas-pictures/monitocam:/recordings
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
